### ISSUE TITLE
[Typo] Java面试题集

### ISSUE THREAD

**Issue by rosuH** [guoxiaoxing/android-interview-guide#1]
在 [Java 面试题集](https://github.com/guoxiaoxing/android-interview/blob/master/doc/Java%E9%9D%A2%E8%AF%95%E9%A2%98%E9%9B%86.md) 文件中的：

> 描述一个类的加载过程？

问题下第五点：

> 5. 对属性就行显示初始化。

1. 缺少一个“进行”的“进”字
2. 是否应该是“显式初始化”而非“显示初始化”

-----
Thanks ~

**Comment by suceser** [comment]
居然有人发现我建了这个repo，这些文章最近在整理，整理好了会发出来。谢谢指正。
