### ISSUE TITLE
亲，Android系统架构图该更新一下了

### ISSUE THREAD

**Issue by NieQing** [guoxiaoxing/android-interview-guide#4]

**Comment by suceser** [comment]
![image](https://user-images.githubusercontent.com/10738148/39556740-21be8b6a-4eb5-11e8-9009-cd082272d721.png)

我感觉这个挺好的=。=

**Comment by NieQing** [comment]
额，这个和source.android.com上面的不太一样呀？

**Comment by suceser** [comment]
嗯，是个详图，大致结构是一样的。
