### ISSUE TITLE
能不能尊重一下我的劳动成果？

### ISSUE THREAD

**Issue by AweiLoveAndroid** [guoxiaoxing/android-interview-guide#6]
应该署名参考我的github吧。。。这个分类和里面的内容和我的一模一样。
https://github.com/AweiLoveAndroid/CommonDevKnowledge/blob/master/interview/summary.md

**Comment by suceser** [comment]
之前没看到过你这个repo，是从掘金搜了一下面试题集，整理了一下问题，写了下答案。我也没去宣传，只是三四月份是面试季，就发出去给大家参考了，而且答案的内容大部分都来源于我的博客。

**Comment by tcqq** [comment]
@AweiLoveAndroid 整合内容的目的只是为了让别人宣传你的名字吗？

**Comment by tcqq** [comment]
我认为分享的意义是帮助他人，我知道你的初心不是不想帮助他人，但如果原文链接对你非常重要，我建议你以后不要公开发表，因为你不能保证所有人都不会犯错。

**Comment by suceser** [comment]
我只是搜集了各种面试题，并把自己博客的内容作为答案放在了里面，本来是自己备忘用的，因为是MIT协议，被鸿洋发到公众号了。我把所有的网页浏览记录都加上了。对你造成的影响深表歉意，而且这是我来阿里之前就写了，请不要带上公司相关信息，谢谢了。
